version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-2GGt5twt3cWlqBuV}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-x1843cmXmuoeQrHD}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD-x1843cmXmuoeQrHD}
    volumes:
      - ./wp-content/plugins/acd-guten-blocks:/var/www/html/wp-content/plugins/acd-guten-blocks
      - ./wp-content/themes/acd:/var/www/html/wp-content/themes/acd
volumes:
  db_data:
    